package plugins

import (
	"fmt"
	plugin_proto "pokemonscan-pokeball/src/proto/proto_struct/plugin"
	"sync"
	"testing"
)

func TestCommon(t *testing.T) {
	p := CommonPlugin{Name: plugin_proto.CommonPluginName, WorkingTasks: &sync.Map{}}
	err := p.Register(nil, ``)
	if err != nil {
		t.Error(err)
	}
	err = p.Run(123, `{
  "image": "pokemonscan/common_python",
  "config": {
    "config_path": "/tmp/config.json",
    "config_content": "{\"target\": \"http://a245089.softether.com.jq.cmc.occpay.com\"}"
  },
  "result_path": "/tmp/result.json",
  "command": "python /tmp/main.py",
  "file": {
    "file_path": "/tmp/main.py",
    "file_content": "aW1wb3J0IGpzb24KZnJvbSBiczQgaW1wb3J0IEJlYXV0aWZ1bFNvdXAKCmltcG9ydCByZXF1ZXN0cwppbXBvcnQgaGFzaGxpYgoKCiMg5LuO5paH5Lu25Lit6Kej5p6QanNvbgpkZWYgcGFyc2VfanNvbl9maWxlKGZpbGVfcGF0aCk6CiAgICB3aXRoIG9wZW4oZmlsZV9wYXRoLCAncicpIGFzIGY6CiAgICAgICAgZGF0YSA9IGpzb24ubG9hZChmKQogICAgcmV0dXJuIGRhdGEKCgojIOivt+axgiDnvZHlnYDlubbojrflj5bov5Tlm57lhoXlrrkKZGVmIGdldF93ZWJzaXRlX3Jlc3AodXJsKToKICAgIHRyeToKICAgICAgICB3aXRoIHJlcXVlc3RzLmdldCh1cmwpIGFzIHI6CiAgICAgICAgICAgIHJldHVybiByLnRleHQKICAgIGV4Y2VwdDoKICAgICAgICByZXR1cm4gIkVycm9yIgoKCiMg6K6h566X6aG16Z2iaGFzaApkZWYgZ2V0X2hhc2godGV4dCk6CiAgICBzb3VwID0gQmVhdXRpZnVsU291cCh0ZXh0LCAnaHRtbC5wYXJzZXInKQoKICAgICMg55SoIEhUTUwg6Kej5p6QIHRleHQgLOW5tuiOt+WPlumhtemdouaJgOacieeahCBjc3Mg5ZKMIEphdmFTY3JpcHQg6ZO+5o6lCiAgICBjc3NfbGlua3MgPSBbXQogICAgZm9yIGxpbmsgaW4gc291cC5maW5kX2FsbCgnbGluaycpOgogICAgICAgIHJlbCA9IGxpbmsuZ2V0KCdyZWwnKQogICAgICAgIGlmIHJlbCBhbmQgJ3N0eWxlc2hlZXQnIGluIHJlbDoKICAgICAgICAgICAgaHJlZiA9IGxpbmsuZ2V0KCdocmVmJykKICAgICAgICAgICAgY3NzX2xpbmtzLmFwcGVuZChocmVmKQoKICAgICMg6I635Y+W5omA5pyJ55qESmF2YVNjcmlwdOmTvuaOpQogICAganNfbGlua3MgPSBbXQogICAgZm9yIHNjcmlwdCBpbiBzb3VwLmZpbmRfYWxsKCdzY3JpcHQnKToKICAgICAgICBzcmMgPSBzY3JpcHQuZ2V0KCdzcmMnKQogICAgICAgIGlmIHNyYzoKICAgICAgICAgICAganNfbGlua3MuYXBwZW5kKHNyYykKCiAgICAjIHByaW50KCdDU1MgTGlua3M6JywgY3NzX2xpbmtzKQogICAgIyBwcmludCgnSmF2YVNjcmlwdCBMaW5rczonLCBqc19saW5rcykKCiAgICBpZiBsZW4oY3NzX2xpbmtzKT4wIG9yIGxlbihqc19saW5rcyk+MDoKICAgICAgICBoYXNoX3N0cmluZyA9ICd8Jy5qb2luKGNzc19saW5rcykgKyAnfCcuam9pbihqc19saW5rcykKICAgIGVsc2U6CiAgICAgICAgaGFzaF9zdHJpbmcgPSB0ZXh0CgoKCgogICAgIyDorqHnrpcgaGFzaF9zdHJpbmcgbWQ1CiAgICBtZDUgPSBoYXNobGliLm1kNSgpCgogICAgIyDmm7TmlrBoYXNobGli5a+56LGh5Lul5aSE55CG5paH5pys5YaF5a65CiAgICBtZDUudXBkYXRlKGhhc2hfc3RyaW5nLmVuY29kZSgndXRmLTgnKSkKCiAgICAjIOiuoeeul+aWh+acrOeahE1ENeWAvAogICAgcmVzdWx0ID0gbWQ1LmhleGRpZ2VzdCgpCiAgICByZXR1cm4gcmVzdWx0CgoKaWYgX19uYW1lX18gPT0gJ19fbWFpbl9fJzoKCiAgICBpbmZvID0ge30KICAgIGluZm9bInVybHMiXSA9IFtdCiAgICBpbmZvWyJob3N0cyJdID0gW10KICAgIGluZm9bImRvbWFpbnMiXSA9IFtdCiAgICBpbmZvWyJ3ZWJzaXRlcyJdID0gW10KICAgIGluZm9bImV4dHJhcyJdID0gW10KICAgIHJlcyA9IHt9CiAgICByZXNbJ2luZm8nXSA9IGluZm8KICAgIHJlc1sndnVsJ10gPSB7fQoKICAgIHRyeToKICAgICAgICBjb25maWdfZGF0YSA9IHBhcnNlX2pzb25fZmlsZSgiL3RtcC9jb25maWcuanNvbiIpCiAgICAgICAgd2Vic2l0ZV9ib2R5ID0gZ2V0X3dlYnNpdGVfcmVzcChjb25maWdfZGF0YVsidGFyZ2V0Il0pCiAgICAgICAgd2Vic2l0ZV9oYXNoID0gZ2V0X2hhc2god2Vic2l0ZV9ib2R5KQogICAgICAgIGluZm9bIndlYnNpdGVzIl0gPSBbeyJ1cmwiOiBjb25maWdfZGF0YVsidGFyZ2V0Il0sICJyZXNwSGFzaCI6IHdlYnNpdGVfaGFzaH1dCgogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgIHByaW50KGUpCgogICAgIyDlsIYgUmVzdWx0IOWGmeWFpSBqc29uIOaWh+S7tgogICAgd2l0aCBvcGVuKCcvdG1wL3Jlc3VsdC5qc29uJywgJ3cnKSBhcyBmOgogICAgICAgIGpzb24uZHVtcChyZXMsIGYsIGluZGVudD00KQo="
}
}`)
	if err != nil {
		t.Error(err)
	}

	info, vuls, err := p.GetResult(123)
	if err != nil {
		t.Error(err)
	}
	fmt.Println(vuls)
	fmt.Println(info)

}
