package plugins

import (
	"fmt"
	plugin_proto "pokemonscan-pokeball/src/proto/proto_struct/plugin"
	"sync"
	"testing"
)

func TestCommon(t *testing.T) {
	p := CommonPlugin{Name: plugin_proto.CommonPluginName, WorkingTasks: &sync.Map{}}
	err := p.Register(nil, ``)
	if err != nil {
		t.Error(err)
	}
	err = p.Run(123, `{
  "image": "pokemonscan/pokeball_common_python",
  "config": {
    "config_path": "/tmp/config.json",
    "config_content": "{\"target\": \"https://www.ctrip.com.hk\"}"
  },
  "result_path": "/tmp/result.json",
  "command": "python /tmp/main.py",
  "file": {
    "file_path": "/tmp/main.py",
    "file_content": "aW1wb3J0IGpzb24KZnJvbSBiczQgaW1wb3J0IEJlYXV0aWZ1bFNvdXAKCmltcG9ydCByZXF1ZXN0cwppbXBvcnQgaGFzaGxpYgoKCiMg5LuO5paH5Lu25Lit6Kej5p6QanNvbgpkZWYgcGFyc2VfanNvbl9maWxlKGZpbGVfcGF0aCk6CiAgICB3aXRoIG9wZW4oZmlsZV9wYXRoLCAncicpIGFzIGY6CiAgICAgICAgZGF0YSA9IGpzb24ubG9hZChmKQogICAgcmV0dXJuIGRhdGEKCgojIOivt+axgiDnvZHlnYDlubbojrflj5bov5Tlm57lhoXlrrkKZGVmIGdldF93ZWJzaXRlX3Jlc3AodXJsKToKICAgIHRyeToKICAgICAgICB3aXRoIHJlcXVlc3RzLmdldCh1cmwpIGFzIHI6CiAgICAgICAgICAgIHNvdXAgPSBCZWF1dGlmdWxTb3VwKHIudGV4dCwgJ2h0bWwucGFyc2VyJykKICAgICAgICAgICAgdGl0bGUgPSBzb3VwLnRpdGxlLnN0cmluZwogICAgICAgICAgICByZXR1cm4gci5zdGF0dXNfY29kZSwgci50ZXh0LCB0aXRsZQogICAgZXhjZXB0OgogICAgICAgIHJldHVybiByLnN0YXR1c19jb2RlLCAiRXJyb3IiLCAiRXJyb3IiCgoKIyDorqHnrpfpobXpnaJoYXNoCmRlZiBnZXRfaGFzaCh0ZXh0KToKICAgIHNvdXAgPSBCZWF1dGlmdWxTb3VwKHRleHQsICdodG1sLnBhcnNlcicpCgogICAgIyDnlKggSFRNTCDop6PmnpAgdGV4dCAs5bm26I635Y+W6aG16Z2i5omA5pyJ55qEIGNzcyDlkowgSmF2YVNjcmlwdCDpk77mjqUKICAgIGNzc19saW5rcyA9IFtdCiAgICBmb3IgbGluayBpbiBzb3VwLmZpbmRfYWxsKCdsaW5rJyk6CiAgICAgICAgcmVsID0gbGluay5nZXQoJ3JlbCcpCiAgICAgICAgaWYgcmVsIGFuZCAnc3R5bGVzaGVldCcgaW4gcmVsOgogICAgICAgICAgICBocmVmID0gbGluay5nZXQoJ2hyZWYnKQogICAgICAgICAgICBjc3NfbGlua3MuYXBwZW5kKGhyZWYpCgogICAgIyDojrflj5bmiYDmnInnmoRKYXZhU2NyaXB06ZO+5o6lCiAgICBqc19saW5rcyA9IFtdCiAgICBmb3Igc2NyaXB0IGluIHNvdXAuZmluZF9hbGwoJ3NjcmlwdCcpOgogICAgICAgIHNyYyA9IHNjcmlwdC5nZXQoJ3NyYycpCiAgICAgICAgaWYgc3JjOgogICAgICAgICAgICBqc19saW5rcy5hcHBlbmQoc3JjKQoKICAgICMgcHJpbnQoJ0NTUyBMaW5rczonLCBjc3NfbGlua3MpCiAgICAjIHByaW50KCdKYXZhU2NyaXB0IExpbmtzOicsIGpzX2xpbmtzKQoKICAgIGlmIGxlbihjc3NfbGlua3MpID4gMCBvciBsZW4oanNfbGlua3MpID4gMDoKICAgICAgICBoYXNoX3N0cmluZyA9ICd8Jy5qb2luKGNzc19saW5rcykgKyAnfCcuam9pbihqc19saW5rcykKICAgIGVsc2U6CiAgICAgICAgaGFzaF9zdHJpbmcgPSB0ZXh0CgogICAgIyDorqHnrpcgaGFzaF9zdHJpbmcgbWQ1CiAgICBtZDUgPSBoYXNobGliLm1kNSgpCgogICAgIyDmm7TmlrBoYXNobGli5a+56LGh5Lul5aSE55CG5paH5pys5YaF5a65CiAgICBtZDUudXBkYXRlKGhhc2hfc3RyaW5nLmVuY29kZSgndXRmLTgnKSkKCiAgICAjIOiuoeeul+aWh+acrOeahE1ENeWAvAogICAgcmVzdWx0ID0gbWQ1LmhleGRpZ2VzdCgpCiAgICByZXR1cm4gcmVzdWx0CgoKaWYgX19uYW1lX18gPT0gJ19fbWFpbl9fJzoKCiAgICBpbmZvID0ge30KICAgIGluZm9bInVybHMiXSA9IFtdCiAgICBpbmZvWyJob3N0cyJdID0gW10KICAgIGluZm9bImRvbWFpbnMiXSA9IFtdCiAgICBpbmZvWyJ3ZWJzaXRlcyJdID0gW10KICAgIGluZm9bImV4dHJhcyJdID0gW10KICAgIHJlcyA9IHt9CiAgICByZXNbJ2luZm8nXSA9IGluZm8KICAgIHJlc1sndnVsJ10gPSB7fQoKICAgIHRyeToKICAgICAgICBjb25maWdfZGF0YSA9IHBhcnNlX2pzb25fZmlsZSgiL3RtcC9jb25maWcuanNvbiIpCiAgICAgICAgc3RhdHVzX2NvZGUsIHdlYnNpdGVfYm9keSwgd2Vic2l0ZV90aXRsZSA9IGdldF93ZWJzaXRlX3Jlc3AoY29uZmlnX2RhdGFbInRhcmdldCJdKQogICAgICAgIHdlYnNpdGVfaGFzaCA9IGdldF9oYXNoKHdlYnNpdGVfYm9keSkKICAgICAgICBpbmZvWyJ3ZWJzaXRlcyJdID0gWwogICAgICAgICAgICB7InVybCI6IGNvbmZpZ19kYXRhWyJ0YXJnZXQiXSwgInJlc3BIYXNoIjogd2Vic2l0ZV9oYXNoLCAic3RhdHVzQ29kZSI6IHN0YXR1c19jb2RlLCAidGl0bGUiOiB3ZWJzaXRlX3RpdGxlLAogICAgICAgICAgICAgInBsdWdpbiI6ICJXZWJzaXRlQ2xlYW5lciJ9XQoKICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICBwcmludChlKQoKICAgICMg5bCGIFJlc3VsdCDlhpnlhaUganNvbiDmlofku7YKICAgIHdpdGggb3BlbignL3RtcC9yZXN1bHQuanNvbicsICd3JykgYXMgZjoKICAgICAgICBqc29uLmR1bXAocmVzLCBmLCBpbmRlbnQ9NCkK"
}
}`)
	if err != nil {
		t.Error(err)
	}

	info, vuls, err := p.GetResult(123)
	if err != nil {
		t.Error(err)
	}
	fmt.Println(vuls)
	fmt.Println(info)

}
