// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: proto/pokeball/pokeball.proto

package pokeball

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 此 pokeball 工作状态
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// repeated int32 taskIds = 2;
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// 正在工作的插件
	Tasks []*TaskArgs `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	// cpu 占用
	Cpu int32 `protobuf:"varint,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	// 内存 占用
	Mem int32 `protobuf:"varint,5,opt,name=mem,proto3" json:"mem,omitempty"`
}

func (x *HeartbeatArgs) Reset() {
	*x = HeartbeatArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatArgs) ProtoMessage() {}

func (x *HeartbeatArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatArgs.ProtoReflect.Descriptor instead.
func (*HeartbeatArgs) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatArgs) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatArgs) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *HeartbeatArgs) GetTasks() []*TaskArgs {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *HeartbeatArgs) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *HeartbeatArgs) GetMem() int32 {
	if x != nil {
		return x.Mem
	}
	return 0
}

type TaskArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId int32  `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Plugin string `protobuf:"bytes,2,opt,name=plugin,proto3" json:"plugin,omitempty"`
}

func (x *TaskArgs) Reset() {
	*x = TaskArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskArgs) ProtoMessage() {}

func (x *TaskArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskArgs.ProtoReflect.Descriptor instead.
func (*TaskArgs) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{1}
}

func (x *TaskArgs) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskArgs) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

type HeartbeatReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 执行操作
	Instruction string `protobuf:"bytes,1,opt,name=Instruction,proto3" json:"Instruction,omitempty"`
}

func (x *HeartbeatReply) Reset() {
	*x = HeartbeatReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReply) ProtoMessage() {}

func (x *HeartbeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReply.ProtoReflect.Descriptor instead.
func (*HeartbeatReply) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatReply) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

type GetTaskArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *GetTaskArgs) Reset() {
	*x = GetTaskArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskArgs) ProtoMessage() {}

func (x *GetTaskArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskArgs.ProtoReflect.Descriptor instead.
func (*GetTaskArgs) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskArgs) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GetTaskReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId     int32  `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	TaskConfig string `protobuf:"bytes,2,opt,name=TaskConfig,proto3" json:"TaskConfig,omitempty"`
}

func (x *GetTaskReply) Reset() {
	*x = GetTaskReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskReply) ProtoMessage() {}

func (x *GetTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskReply.ProtoReflect.Descriptor instead.
func (*GetTaskReply) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskReply) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *GetTaskReply) GetTaskConfig() string {
	if x != nil {
		return x.TaskConfig
	}
	return ""
}

type ContinueTaskReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks []*TaskArgs `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *ContinueTaskReply) Reset() {
	*x = ContinueTaskReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContinueTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueTaskReply) ProtoMessage() {}

func (x *ContinueTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueTaskReply.ProtoReflect.Descriptor instead.
func (*ContinueTaskReply) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{5}
}

func (x *ContinueTaskReply) GetTasks() []*TaskArgs {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetRegisteredConfigArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash     string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ConfigId int32  `protobuf:"varint,2,opt,name=ConfigId,proto3" json:"ConfigId,omitempty"`
	Version  string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *GetRegisteredConfigArgs) Reset() {
	*x = GetRegisteredConfigArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRegisteredConfigArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegisteredConfigArgs) ProtoMessage() {}

func (x *GetRegisteredConfigArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegisteredConfigArgs.ProtoReflect.Descriptor instead.
func (*GetRegisteredConfigArgs) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{6}
}

func (x *GetRegisteredConfigArgs) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GetRegisteredConfigArgs) GetConfigId() int32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *GetRegisteredConfigArgs) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetRegisteredConfigReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegisteredConfig string `protobuf:"bytes,1,opt,name=RegisteredConfig,proto3" json:"RegisteredConfig,omitempty"`
}

func (x *GetRegisteredConfigReply) Reset() {
	*x = GetRegisteredConfigReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRegisteredConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegisteredConfigReply) ProtoMessage() {}

func (x *GetRegisteredConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegisteredConfigReply.ProtoReflect.Descriptor instead.
func (*GetRegisteredConfigReply) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{7}
}

func (x *GetRegisteredConfigReply) GetRegisteredConfig() string {
	if x != nil {
		return x.RegisteredConfig
	}
	return ""
}

type ReportInfoArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 上报目前收集到的所有资产信息
	TaskId   int32          `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Urls     []*UrlInfo     `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
	Hosts    []*HostInfo    `protobuf:"bytes,3,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Websites []*WebsiteInfo `protobuf:"bytes,4,rep,name=websites,proto3" json:"websites,omitempty"`
	Domains  []*DomainInfo  `protobuf:"bytes,5,rep,name=domains,proto3" json:"domains,omitempty"`
	Extras   []*ExtraInfo   `protobuf:"bytes,6,rep,name=extras,proto3" json:"extras,omitempty"`
}

func (x *ReportInfoArgs) Reset() {
	*x = ReportInfoArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportInfoArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInfoArgs) ProtoMessage() {}

func (x *ReportInfoArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInfoArgs.ProtoReflect.Descriptor instead.
func (*ReportInfoArgs) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{8}
}

func (x *ReportInfoArgs) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ReportInfoArgs) GetUrls() []*UrlInfo {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *ReportInfoArgs) GetHosts() []*HostInfo {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *ReportInfoArgs) GetWebsites() []*WebsiteInfo {
	if x != nil {
		return x.Websites
	}
	return nil
}

func (x *ReportInfoArgs) GetDomains() []*DomainInfo {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *ReportInfoArgs) GetExtras() []*ExtraInfo {
	if x != nil {
		return x.Extras
	}
	return nil
}

type ReportInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReportInfoReply) Reset() {
	*x = ReportInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInfoReply) ProtoMessage() {}

func (x *ReportInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInfoReply.ProtoReflect.Descriptor instead.
func (*ReportInfoReply) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{9}
}

type CompletionStatusArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 上报完成的任务
	TaskId int32 `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
}

func (x *CompletionStatusArgs) Reset() {
	*x = CompletionStatusArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletionStatusArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionStatusArgs) ProtoMessage() {}

func (x *CompletionStatusArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionStatusArgs.ProtoReflect.Descriptor instead.
func (*CompletionStatusArgs) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{10}
}

func (x *CompletionStatusArgs) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type CompletionStatusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CompletionStatusReply) Reset() {
	*x = CompletionStatusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletionStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionStatusReply) ProtoMessage() {}

func (x *CompletionStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionStatusReply.ProtoReflect.Descriptor instead.
func (*CompletionStatusReply) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{11}
}

type HostInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host        string         `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	HostService []*HostService `protobuf:"bytes,2,rep,name=hostService,proto3" json:"hostService,omitempty"`
	Plugin      string         `protobuf:"bytes,3,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Invalid     bool           `protobuf:"varint,4,opt,name=invalid,proto3" json:"invalid,omitempty"`
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{12}
}

func (x *HostInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HostInfo) GetHostService() []*HostService {
	if x != nil {
		return x.HostService
	}
	return nil
}

func (x *HostInfo) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *HostInfo) GetInvalid() bool {
	if x != nil {
		return x.Invalid
	}
	return false
}

type HostService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port int32  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HostService) Reset() {
	*x = HostService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostService) ProtoMessage() {}

func (x *HostService) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostService.ProtoReflect.Descriptor instead.
func (*HostService) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{13}
}

func (x *HostService) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HostService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UrlInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url     string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method  string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Body    string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Headers string `protobuf:"bytes,4,opt,name=headers,proto3" json:"headers,omitempty"`
	Tag     string `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	Hit     string `protobuf:"bytes,6,opt,name=hit,proto3" json:"hit,omitempty"`
}

func (x *UrlInfo) Reset() {
	*x = UrlInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UrlInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlInfo) ProtoMessage() {}

func (x *UrlInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlInfo.ProtoReflect.Descriptor instead.
func (*UrlInfo) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{14}
}

func (x *UrlInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UrlInfo) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *UrlInfo) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *UrlInfo) GetHeaders() string {
	if x != nil {
		return x.Headers
	}
	return ""
}

func (x *UrlInfo) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *UrlInfo) GetHit() string {
	if x != nil {
		return x.Hit
	}
	return ""
}

type WebsiteInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url         string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Fingerprint string `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	StatusCode  int32  `protobuf:"varint,4,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Length      int32  `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	Server      string `protobuf:"bytes,6,opt,name=server,proto3" json:"server,omitempty"`
	Address     string `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	IsCDN       int32  `protobuf:"varint,8,opt,name=isCDN,proto3" json:"isCDN,omitempty"`
	Asn         string `protobuf:"bytes,9,opt,name=asn,proto3" json:"asn,omitempty"`
	Org         string `protobuf:"bytes,10,opt,name=org,proto3" json:"org,omitempty"`
	Plugin      string `protobuf:"bytes,11,opt,name=plugin,proto3" json:"plugin,omitempty"`
	RespHash    string `protobuf:"bytes,12,opt,name=respHash,proto3" json:"respHash,omitempty"`
}

func (x *WebsiteInfo) Reset() {
	*x = WebsiteInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebsiteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsiteInfo) ProtoMessage() {}

func (x *WebsiteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsiteInfo.ProtoReflect.Descriptor instead.
func (*WebsiteInfo) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{15}
}

func (x *WebsiteInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebsiteInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WebsiteInfo) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *WebsiteInfo) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *WebsiteInfo) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *WebsiteInfo) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *WebsiteInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WebsiteInfo) GetIsCDN() int32 {
	if x != nil {
		return x.IsCDN
	}
	return 0
}

func (x *WebsiteInfo) GetAsn() string {
	if x != nil {
		return x.Asn
	}
	return ""
}

func (x *WebsiteInfo) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *WebsiteInfo) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *WebsiteInfo) GetRespHash() string {
	if x != nil {
		return x.RespHash
	}
	return ""
}

type DomainInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ip     string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Cname  string `protobuf:"bytes,3,opt,name=cname,proto3" json:"cname,omitempty"`
	Plugin string `protobuf:"bytes,4,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Root   bool   `protobuf:"varint,5,opt,name=root,proto3" json:"root,omitempty"`
}

func (x *DomainInfo) Reset() {
	*x = DomainInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DomainInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainInfo) ProtoMessage() {}

func (x *DomainInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainInfo.ProtoReflect.Descriptor instead.
func (*DomainInfo) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{16}
}

func (x *DomainInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DomainInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *DomainInfo) GetCname() string {
	if x != nil {
		return x.Cname
	}
	return ""
}

func (x *DomainInfo) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *DomainInfo) GetRoot() bool {
	if x != nil {
		return x.Root
	}
	return false
}

type ReportVulArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 上报目前收集到的所有资产信息
	TaskId int32      `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Vuls   []*VulInfo `protobuf:"bytes,2,rep,name=vuls,proto3" json:"vuls,omitempty"`
}

func (x *ReportVulArgs) Reset() {
	*x = ReportVulArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportVulArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportVulArgs) ProtoMessage() {}

func (x *ReportVulArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportVulArgs.ProtoReflect.Descriptor instead.
func (*ReportVulArgs) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{17}
}

func (x *ReportVulArgs) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ReportVulArgs) GetVuls() []*VulInfo {
	if x != nil {
		return x.Vuls
	}
	return nil
}

type ReportVulReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReportVulReply) Reset() {
	*x = ReportVulReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportVulReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportVulReply) ProtoMessage() {}

func (x *ReportVulReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportVulReply.ProtoReflect.Descriptor instead.
func (*ReportVulReply) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{18}
}

type VulInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Url    string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Plugin string `protobuf:"bytes,3,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Detail string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *VulInfo) Reset() {
	*x = VulInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VulInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VulInfo) ProtoMessage() {}

func (x *VulInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VulInfo.ProtoReflect.Descriptor instead.
func (*VulInfo) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{19}
}

func (x *VulInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *VulInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *VulInfo) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *VulInfo) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ExtraInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Short  string `protobuf:"bytes,2,opt,name=short,proto3" json:"short,omitempty"`
	Detail string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Plugin string `protobuf:"bytes,4,opt,name=plugin,proto3" json:"plugin,omitempty"`
}

func (x *ExtraInfo) Reset() {
	*x = ExtraInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokeball_pokeball_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtraInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraInfo) ProtoMessage() {}

func (x *ExtraInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokeball_pokeball_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraInfo.ProtoReflect.Descriptor instead.
func (*ExtraInfo) Descriptor() ([]byte, []int) {
	return file_proto_pokeball_pokeball_proto_rawDescGZIP(), []int{20}
}

func (x *ExtraInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExtraInfo) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *ExtraInfo) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ExtraInfo) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

var File_proto_pokeball_pokeball_proto protoreflect.FileDescriptor

var file_proto_pokeball_pokeball_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c,
	0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x16, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70,
	0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x22, 0x97, 0x01, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x62, 0x65, 0x61, 0x74, 0x41, 0x72, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x36, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x63, 0x70, 0x75, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x65, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x65,
	0x6d, 0x22, 0x3a, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74,
	0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x22, 0x32, 0x0a,
	0x0e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x20, 0x0a, 0x0b, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x21, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x22, 0x46, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x4b, 0x0a, 0x11,
	0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x36, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x72,
	0x67, 0x73, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x22, 0x63, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x46,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x10, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0xcf, 0x02, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x72, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x12, 0x33, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x2e, 0x55, 0x72, 0x6c, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x12, 0x36, 0x0a, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x2e, 0x48,
	0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x3f,
	0x0a, 0x08, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x2e, 0x57, 0x65, 0x62, 0x73, 0x69, 0x74,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x73, 0x12,
	0x3c, 0x0a, 0x07, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x39, 0x0a,
	0x06, 0x65, 0x78, 0x74, 0x72, 0x61, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x6f,
	0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x06, 0x65, 0x78, 0x74, 0x72, 0x61, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2e, 0x0a, 0x14, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41,
	0x72, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x97, 0x01, 0x0a, 0x08, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x45, 0x0a, 0x0b, 0x68, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x62,
	0x61, 0x6c, 0x6c, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x0b, 0x68, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x35,
	0x0a, 0x0b, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x07, 0x55, 0x72, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x68,
	0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x68, 0x69, 0x74, 0x22, 0xaf, 0x02,
	0x0a, 0x0b, 0x57, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70,
	0x72, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x67,
	0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x43, 0x44, 0x4e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x69, 0x73, 0x43, 0x44, 0x4e, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x73, 0x6e, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x73, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x72, 0x67,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x72, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x48, 0x61, 0x73, 0x68, 0x22,
	0x72, 0x0a, 0x0a, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x70, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x63, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x72,
	0x6f, 0x6f, 0x74, 0x22, 0x5c, 0x0a, 0x0d, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x56, 0x75, 0x6c,
	0x41, 0x72, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x04,
	0x76, 0x75, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x62,
	0x61, 0x6c, 0x6c, 0x2e, 0x56, 0x75, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x76, 0x75, 0x6c,
	0x73, 0x22, 0x10, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x56, 0x75, 0x6c, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x5f, 0x0a, 0x07, 0x56, 0x75, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x22, 0x65, 0x0a, 0x09, 0x45, 0x78, 0x74, 0x72, 0x61, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x32, 0xd7, 0x05, 0x0a, 0x0b,
	0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5a, 0x0a, 0x09, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x25, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c,
	0x6c, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x41, 0x72, 0x67, 0x73, 0x1a,
	0x26, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65,
	0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x54, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54, 0x61,
	0x73, 0x6b, 0x12, 0x23, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x24, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5e, 0x0a,
	0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x23, 0x2e,
	0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x6f,
	0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x72,
	0x67, 0x73, 0x1a, 0x29, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x69, 0x6e, 0x75, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x78, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x2f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x30, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x63, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x26, 0x2e, 0x70, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x6f, 0x6b, 0x65,
	0x62, 0x61, 0x6c, 0x6c, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x41,
	0x72, 0x67, 0x73, 0x1a, 0x27, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x2e, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x60, 0x0a, 0x0f,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x56, 0x75, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x25, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x56,
	0x75, 0x6c, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x26, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x2e,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x56, 0x75, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x75,
	0x0a, 0x16, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2c, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c,
	0x6c, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x2d, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x18, 0x5a, 0x16, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x62, 0x61, 0x6c, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_pokeball_pokeball_proto_rawDescOnce sync.Once
	file_proto_pokeball_pokeball_proto_rawDescData = file_proto_pokeball_pokeball_proto_rawDesc
)

func file_proto_pokeball_pokeball_proto_rawDescGZIP() []byte {
	file_proto_pokeball_pokeball_proto_rawDescOnce.Do(func() {
		file_proto_pokeball_pokeball_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pokeball_pokeball_proto_rawDescData)
	})
	return file_proto_pokeball_pokeball_proto_rawDescData
}

var file_proto_pokeball_pokeball_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_pokeball_pokeball_proto_goTypes = []interface{}{
	(*HeartbeatArgs)(nil),            // 0: pokemon.proto.pokeball.HeartbeatArgs
	(*TaskArgs)(nil),                 // 1: pokemon.proto.pokeball.TaskArgs
	(*HeartbeatReply)(nil),           // 2: pokemon.proto.pokeball.HeartbeatReply
	(*GetTaskArgs)(nil),              // 3: pokemon.proto.pokeball.GetTaskArgs
	(*GetTaskReply)(nil),             // 4: pokemon.proto.pokeball.GetTaskReply
	(*ContinueTaskReply)(nil),        // 5: pokemon.proto.pokeball.ContinueTaskReply
	(*GetRegisteredConfigArgs)(nil),  // 6: pokemon.proto.pokeball.GetRegisteredConfigArgs
	(*GetRegisteredConfigReply)(nil), // 7: pokemon.proto.pokeball.GetRegisteredConfigReply
	(*ReportInfoArgs)(nil),           // 8: pokemon.proto.pokeball.ReportInfoArgs
	(*ReportInfoReply)(nil),          // 9: pokemon.proto.pokeball.ReportInfoReply
	(*CompletionStatusArgs)(nil),     // 10: pokemon.proto.pokeball.CompletionStatusArgs
	(*CompletionStatusReply)(nil),    // 11: pokemon.proto.pokeball.CompletionStatusReply
	(*HostInfo)(nil),                 // 12: pokemon.proto.pokeball.HostInfo
	(*HostService)(nil),              // 13: pokemon.proto.pokeball.HostService
	(*UrlInfo)(nil),                  // 14: pokemon.proto.pokeball.UrlInfo
	(*WebsiteInfo)(nil),              // 15: pokemon.proto.pokeball.WebsiteInfo
	(*DomainInfo)(nil),               // 16: pokemon.proto.pokeball.DomainInfo
	(*ReportVulArgs)(nil),            // 17: pokemon.proto.pokeball.ReportVulArgs
	(*ReportVulReply)(nil),           // 18: pokemon.proto.pokeball.ReportVulReply
	(*VulInfo)(nil),                  // 19: pokemon.proto.pokeball.VulInfo
	(*ExtraInfo)(nil),                // 20: pokemon.proto.pokeball.ExtraInfo
}
var file_proto_pokeball_pokeball_proto_depIdxs = []int32{
	1,  // 0: pokemon.proto.pokeball.HeartbeatArgs.tasks:type_name -> pokemon.proto.pokeball.TaskArgs
	1,  // 1: pokemon.proto.pokeball.ContinueTaskReply.tasks:type_name -> pokemon.proto.pokeball.TaskArgs
	14, // 2: pokemon.proto.pokeball.ReportInfoArgs.urls:type_name -> pokemon.proto.pokeball.UrlInfo
	12, // 3: pokemon.proto.pokeball.ReportInfoArgs.hosts:type_name -> pokemon.proto.pokeball.HostInfo
	15, // 4: pokemon.proto.pokeball.ReportInfoArgs.websites:type_name -> pokemon.proto.pokeball.WebsiteInfo
	16, // 5: pokemon.proto.pokeball.ReportInfoArgs.domains:type_name -> pokemon.proto.pokeball.DomainInfo
	20, // 6: pokemon.proto.pokeball.ReportInfoArgs.extras:type_name -> pokemon.proto.pokeball.ExtraInfo
	13, // 7: pokemon.proto.pokeball.HostInfo.hostService:type_name -> pokemon.proto.pokeball.HostService
	19, // 8: pokemon.proto.pokeball.ReportVulArgs.vuls:type_name -> pokemon.proto.pokeball.VulInfo
	0,  // 9: pokemon.proto.pokeball.TaskService.Heartbeat:input_type -> pokemon.proto.pokeball.HeartbeatArgs
	3,  // 10: pokemon.proto.pokeball.TaskService.GetTask:input_type -> pokemon.proto.pokeball.GetTaskArgs
	3,  // 11: pokemon.proto.pokeball.TaskService.ContinueTask:input_type -> pokemon.proto.pokeball.GetTaskArgs
	6,  // 12: pokemon.proto.pokeball.TaskService.GetRegisteredConfig:input_type -> pokemon.proto.pokeball.GetRegisteredConfigArgs
	8,  // 13: pokemon.proto.pokeball.TaskService.ReportInfoResult:input_type -> pokemon.proto.pokeball.ReportInfoArgs
	17, // 14: pokemon.proto.pokeball.TaskService.ReportVulResult:input_type -> pokemon.proto.pokeball.ReportVulArgs
	10, // 15: pokemon.proto.pokeball.TaskService.ReportCompletionStatus:input_type -> pokemon.proto.pokeball.CompletionStatusArgs
	2,  // 16: pokemon.proto.pokeball.TaskService.Heartbeat:output_type -> pokemon.proto.pokeball.HeartbeatReply
	4,  // 17: pokemon.proto.pokeball.TaskService.GetTask:output_type -> pokemon.proto.pokeball.GetTaskReply
	5,  // 18: pokemon.proto.pokeball.TaskService.ContinueTask:output_type -> pokemon.proto.pokeball.ContinueTaskReply
	7,  // 19: pokemon.proto.pokeball.TaskService.GetRegisteredConfig:output_type -> pokemon.proto.pokeball.GetRegisteredConfigReply
	9,  // 20: pokemon.proto.pokeball.TaskService.ReportInfoResult:output_type -> pokemon.proto.pokeball.ReportInfoReply
	18, // 21: pokemon.proto.pokeball.TaskService.ReportVulResult:output_type -> pokemon.proto.pokeball.ReportVulReply
	11, // 22: pokemon.proto.pokeball.TaskService.ReportCompletionStatus:output_type -> pokemon.proto.pokeball.CompletionStatusReply
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_pokeball_pokeball_proto_init() }
func file_proto_pokeball_pokeball_proto_init() {
	if File_proto_pokeball_pokeball_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pokeball_pokeball_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContinueTaskReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRegisteredConfigArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRegisteredConfigReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportInfoArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompletionStatusArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompletionStatusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UrlInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebsiteInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DomainInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportVulArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportVulReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VulInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokeball_pokeball_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtraInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pokeball_pokeball_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pokeball_pokeball_proto_goTypes,
		DependencyIndexes: file_proto_pokeball_pokeball_proto_depIdxs,
		MessageInfos:      file_proto_pokeball_pokeball_proto_msgTypes,
	}.Build()
	File_proto_pokeball_pokeball_proto = out.File
	file_proto_pokeball_pokeball_proto_rawDesc = nil
	file_proto_pokeball_pokeball_proto_goTypes = nil
	file_proto_pokeball_pokeball_proto_depIdxs = nil
}
