name: Build  Pokeball Artifact
on:
  #监听push操作
  push:
    branches:
      # master分支，你也可以改成其他分支
      - master
      - main
jobs:
  pokeball:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: recursive
      - name: build
        run: ./script/build_pokeball.sh
      - name: PokeBall Artifact
        uses: actions/upload-artifact@v3
        with:
          name: worker_pokeball
          path: build/pokeball.tar.gz
          retention-days: 1
