name: Build  Pokeball Artifact
on:
  #监听push操作
  push:
    branches:
      # master分支，你也可以改成其他分支
      - master
      - main
jobs:
  pokeball:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
#    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.22.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    # Use a container with GLIBC 2.17
    container: quay.io/pypa/manylinux2014_x86_64
    timeout-minutes: 30
    steps:
      - name: Show GLIBC
        run: ldd --version
      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.21
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: build
        run: ./script/build_pokeball.sh
      - name: PokeBall Artifact
        uses: actions/upload-artifact@v3
        with:
          name: worker_pokeball
          path: build/pokeball.tar.gz
          retention-days: 1
